"""
Django settings for my_movies_diary project.






















































































































































echo -e "${YELLOW}To rollback: Copy backup and reload nginx${NC}"echo ""echo -e "   ${GREEN}bash migrate-to-https-final.sh${NC}"echo "2. When ready to redirect HTTP to HTTPS, run:"echo ""echo "   - All features"echo "   - API calls"echo "   - Login/logout"echo "1. Test thoroughly for 10-15 minutes"echo -e "${YELLOW}Next Steps:${NC}"echo ""echo "  ✓ HTTPS: Working (https://moviediary.live)"echo "  ✓ HTTP: Working (http://moviediary.live)"echo "Current Status:"echo ""echo -e "${BLUE}================================================${NC}"echo -e "${GREEN}Phase 1 Complete!${NC}"echo -e "${BLUE}================================================${NC}"echo ""fi    echo -e "${YELLOW}⚠ HTTP test returned non-200 status${NC}"else    echo -e "${GREEN}✓ HTTP still working${NC}"if curl -s -o /dev/null -w "%{http_code}" http://moviediary.live | grep -q "200"; then# Test HTTP still worksfi    echo "  Check: https://moviediary.live in your browser"    echo -e "${YELLOW}⚠ HTTPS test returned non-200 status${NC}"else    echo -e "${GREEN}✓ HTTPS is working!${NC}"if curl -s -o /dev/null -w "%{http_code}" https://moviediary.live | grep -q "200"; then# Test HTTPSsleep 3echo "Testing HTTPS functionality..."echo -e "${YELLOW}Step 6: Testing Phase${NC}"echo ""echo -e "${GREEN}✓ HTTPS enabled!${NC}"docker-compose exec nginx nginx -s reloadcp nginx/nginx.conf.step2 nginx/nginx.confconfirm "Continue?"echo -e "${YELLOW}Step 5: Enable HTTPS (HTTP still works too)${NC}"echo ""fi    exit 1    echo "Check logs: docker-compose logs certbot"    echo -e "${RED}✗ Certificate request failed${NC}"else    echo -e "${GREEN}✓ SSL Certificates obtained successfully${NC}"if [ $? -eq 0 ]; then./init-letsencrypt.shchmod +x init-letsencrypt.shconfirm "Continue?"echo "This will request certificates from Let's Encrypt"echo -e "${YELLOW}Step 4: Obtain SSL Certificates${NC}"echo ""fi    exit 1    echo -e "${RED}✗ init-letsencrypt.sh not found${NC}"if [ ! -f "init-letsencrypt.sh" ]; thenconfirm "Have you edited init-letsencrypt.sh with your details?"echo -e "${RED}IMPORTANT: Update the email address!${NC}"echo ""echo "  - email=\"your-email@example.com\""echo "  - domains=(moviediary.live www.moviediary.live)"echo "Edit init-letsencrypt.sh and set:"echo -e "${YELLOW}Step 3: Configure init-letsencrypt.sh${NC}"echo ""fi    exit 1    docker-compose restart nginx    cp nginx/nginx.conf.backup.* nginx/nginx.conf    echo -e "${RED}✗ Nginx failed to start. Restoring backup...${NC}"else    echo -e "${GREEN}✓ HTTP still working, SSL validation path ready${NC}"    echo -e "${GREEN}✓ Nginx restarted successfully${NC}"if check_service "nginx"; thensleep 2docker-compose up -d nginxcp nginx/nginx.conf.step1 nginx/nginx.confconfirm "Continue?"echo "This keeps HTTP working while preparing for SSL certificates"echo -e "${YELLOW}Step 2: Prepare Nginx for SSL Validation${NC}"echo ""fi    exit 1    echo -e "${RED}✗ nginx.conf not found${NC}"else    echo -e "${GREEN}✓ Backup created${NC}"    cp nginx/nginx.conf nginx/nginx.conf.backup.$(date +%Y%m%d_%H%M%S)if [ -f "nginx/nginx.conf" ]; thenecho -e "${YELLOW}Step 1: Backup Current Configuration${NC}"echo ""check_service "frontend"check_service "backend"check_service "nginx" || { echo "Please start your application first"; exit 1; }echo -e "${YELLOW}Current Status Check:${NC}"}    fi        return 1        echo -e "${RED}✗ $1 is not running${NC}"    else        return 0        echo -e "${GREEN}✓ $1 is running${NC}"    if docker-compose ps | grep -q "$1.*Up"; thencheck_service() {# Function to check if service is running}    fi        exit 1        echo -e "${RED}Aborted by user${NC}"    if [[ ! $REPLY =~ ^[Yy]$ ]]; then    echo    read -p "$1 (y/n): " -n 1 -rconfirm() {# Function to prompt userecho ""echo -e "${BLUE}================================================${NC}"echo -e "${BLUE}  Safe HTTPS Migration - Zero Downtime  ${NC}"echo -e "${BLUE}================================================${NC}"NC='\033[0m' # No ColorBLUE='\033[0;34m'YELLOW='\033[1;33m'GREEN='\033[0;32m'RED='\033[0;31m'set -e# Run this on your production server# Safe HTTPS Migration Script
Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_KEY", "django-default-key-for-dev")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

# Basic Security Settings
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'SAMEORIGIN'
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    
    # HTTPS Security Settings
    # Note: Enable these AFTER HTTPS is fully working and redirecting
    # See SAFE_HTTPS_MIGRATION.md for step-by-step instructions
    USE_HTTPS = os.environ.get("USE_HTTPS", "False") == "True"
    
    if USE_HTTPS:
        SECURE_SSL_REDIRECT = True
        SESSION_COOKIE_SECURE = True
        CSRF_COOKIE_SECURE = True
        SECURE_HSTS_SECONDS = 31536000  # 1 year
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = True
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    # Local apps
    'base',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise for static files
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware (must be before CommonMiddleware)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'my_movies_diary.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_movies_diary.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get("DB"),
        'USER': os.environ.get("DB_USER"),
        'PASSWORD': os.environ.get("DB_PASSWORD"),
        'HOST': os.environ.get("DB_HOST"),
        'PORT': os.environ.get("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration for serving static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# TMDB API Configuration
TMDB_API_KEY = os.environ.get("API_KEY")
TMDB_MOVIE_ENDPOINT = os.environ.get("MOVIE_ENDPOINT")
TMDB_IMG_URL = "https://image.tmdb.org/t/p/w500"

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'
LOGIN_URL = 'login'

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
}

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS settings - allows React frontend to communicate with Django backend
CORS_ALLOWED_ORIGINS = os.environ.get(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:5173,http://localhost:3000,http://127.0.0.1:5173,http://127.0.0.1:3000"
).split(",")

CORS_ALLOW_CREDENTIALS = True
# CORS_ALLOW_ALL_ORIGINS = True 